const AUTH_ACTION_TYPES = {
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOADING_USER: "LOADING_USER",
  SET_USER: "SET_USER",
  SIGN_UP_USER_LOADING: "SIGN_UP_USER_LOADING",
  LOGGIN_OUT_USER: "LOGGIN_OUT_USER",
};

export default AUTH_ACTION_TYPES;
