const MEAL_ACTION_TYPES = {
  LOADING_MEALS: "LOADING_MEALS",
  SET_MEALS: "SET_MEALS",
  ADDING_NEW_MEAL: "ADDING_NEW_MEAL",
  SET_NEW_MEAL: "SET_NEW_MEAL",
  DELETING_MEALS: "DELETING_MEALS",
  DELETE_MEAL: "DELETE_MEAL",
};

export default MEAL_ACTION_TYPES;
